--------------------------------------------------------
--  File created - Friday-October-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DALTONACCOUNTS
--------------------------------------------------------

  CREATE TABLE "ORA1"."DALTONACCOUNTS" 
   (	"ACCOUNTID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"CUSTOMERID" NUMBER(*,0), 
	"ACCOUNTNUMBER" NUMBER, 
	"DATEOPENED" DATE, 
	"DATECLOSED" DATE, 
	"ACCOUNTTYPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DALTONCUSTOMERS
--------------------------------------------------------

  CREATE TABLE "ORA1"."DALTONCUSTOMERS" 
   (	"CUSTOMERID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"NAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE), 
	"ZIP" VARCHAR2(6 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DALTONTRANSACTIONS
--------------------------------------------------------

  CREATE TABLE "ORA1"."DALTONTRANSACTIONS" 
   (	"TRANSACTIONID" NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE , 
	"ACCOUNTID" NUMBER(*,0), 
	"TRANSACTIONDATE" DATE, 
	"AMOUNT" NUMBER, 
	"TRANSACTTYPE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010942
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0010942" ON "ORA1"."DALTONACCOUNTS" ("ACCOUNTID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010946
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0010946" ON "ORA1"."DALTONCUSTOMERS" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010944
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."SYS_C0010944" ON "ORA1"."DALTONTRANSACTIONS" ("TRANSACTIONID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DALTONACCOUNTS
--------------------------------------------------------

  ALTER TABLE "ORA1"."DALTONACCOUNTS" ADD PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."DALTONACCOUNTS" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DALTONCUSTOMERS
--------------------------------------------------------

  ALTER TABLE "ORA1"."DALTONCUSTOMERS" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."DALTONCUSTOMERS" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DALTONTRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "ORA1"."DALTONTRANSACTIONS" ADD PRIMARY KEY ("TRANSACTIONID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "ORA1"."DALTONTRANSACTIONS" MODIFY ("TRANSACTIONID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table DALTONACCOUNTS
--------------------------------------------------------

  ALTER TABLE "ORA1"."DALTONACCOUNTS" ADD CONSTRAINT "DALTONACCOUNTS_FK1" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "ORA1"."DALTONCUSTOMERS" ("CUSTOMERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DALTONTRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "ORA1"."DALTONTRANSACTIONS" ADD CONSTRAINT "DALTONTRANSACTIONS_FK1" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES "ORA1"."DALTONACCOUNTS" ("ACCOUNTID") ENABLE;
    
    
    INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Signe Mays','P.O. Box 889, 6763 Nisi St.','Gulfport','MS','1725');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Ethan Jenkins','Ap #510-6082 Est, Av.','San Francisco','H','23344');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Nigel Moore','6997 Et St.','Toulouse','Midi-Pyrénées','11595');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kalia Kaufman','P.O. Box 621, 6674 Condimentum. St.','Borlänge','W','356961');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Murphy Jacobs','413-7591 Ornare, St.','Mildura','Victoria','31707');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Larissa Lamb','P.O. Box 621, 5776 Vitae Ave','Gijón','Principado de Asturias','80374-134');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Ursula Dodson','2766 Ultrices. St.','Patarrá','San José','27185');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Patrick Medina','Ap #452-4316 Duis Rd.','Eugene','OR','71708');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Ashton Fernandez','P.O. Box 261, 7713 Fames Ave','Vienna','Wie','83119');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Zahir Hodges','1171 In Rd.','Lublin','Lubelskie','6829');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Colette Petersen','1210 Urna Av.','Belfast','Ulster','463062');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Sandra Lindsey','1289 Libero St.','Istanbul','Istanbul','41072');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Wing Ingram','6023 Volutpat. St.','Dublin','L','35893');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Quamar Watkins','936-352 Ornare St.','Hervey Bay','Queensland','71754');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Hope Briggs','P.O. Box 973, 1850 Nisi. Road','Chandler','Arizona','34364');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Elton Alvarado','Ap #899-3582 Ipsum Street','Baracaldo','Euskadi','61660');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Hammett Baxter','537-7780 Auctor, Street','Baie-Comeau','QC','T8 4VP');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Alana Glass','P.O. Box 625, 3296 Mauris Av.','Vilvoorde','Vlaams-Brabant','5157');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Caleb Navarro','P.O. Box 103, 1614 Senectus Road','Jönköping','F','9299');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Randall Brown','Ap #384-2507 Vel Street','Kidderminster','WO','4860');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Jacqueline Baxter','P.O. Box 924, 3162 Lacus St.','Barranca','P','3102');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Josiah Rios','P.O. Box 542, 9629 Duis St.','Dublin','Leinster','42-614');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Carol Oneill','2303 Fringilla Avenue','Redcliffe','QLD','369493');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Hunter Puckett','8146 Rhoncus. Street','Tejar','Cartago','62035-775');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Brendan Chen','322-1562 Feugiat. Avenue','Ville-en-Hesbaye','LU','33774');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rahim Hardy','Ap #582-2270 At, Av.','Palmerston North','North Island','732074');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Stone Booker','727-2365 Montes, Rd.','Berlin','BE','4876');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Mufutau Ashley','Ap #161-6746 Mauris Road','Cork','M','G2W 5J8');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Alexander Mosley','P.O. Box 556, 8696 Quis Street','Merksem','Antwerpen','60409');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Caldwell Herman','481-6581 Fringilla. St.','Täby','Stockholms län','81339');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Chanda Barnett','P.O. Box 229, 2144 Iaculis Road','Port Hope','ON','4256');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rama William','Ap #876-5987 Sem Rd.','Springfield','Massachusetts','XN9 3PU');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('India Alvarez','Ap #957-9795 Egestas Street','Butte','Montana','33748');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kalia Rosales','P.O. Box 142, 5429 Praesent Ave','Betim','MG','4568ML');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Lacota Mcclure','450-882 Sed St.','Korba','Chhattisgarh','36261');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Ethan Jefferson','994-7575 Nibh. Rd.','Lidköping','Västra Götalands län','69495');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Dakota Kelly','935-6805 Integer St.','Sromness','OK','81760');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Anjolie Whitley','Ap #192-9349 Ultrices. St.','Waitara','NI','44-088');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Talon England','8564 Consequat St.','Jaboatão dos Guararapes','Pernambuco','25617');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Malcolm Michael','P.O. Box 837, 1001 Lacus. Rd.','Güstrow','MV','9602');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Gwendolyn Miranda','P.O. Box 875, 9393 Sed Rd.','Bierk Bierghes','WB','2900');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('TaShya Huffman','197-2582 Proin St.','Gdynia','Pomorskie','51410');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Mira Holloway','8607 Senectus Street','Dutse','JI','51617');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Logan Randolph','Ap #448-2753 Ut St.','Fayetteville','Arkansas','39945');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kyra Irwin','Ap #109-4239 Mollis. St.','Hamburg','Hamburg','4923');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Colt Levine','Ap #363-4840 Non Street','Anchorage','Alaska','R4P 4H2');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Victor Kelley','670-6790 Lectus St.','Lambersart','NO','551057');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Delilah Hartman','Ap #812-8080 Integer Av.','Poznań','WP','74214');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Vera Jordan','P.O. Box 999, 3402 Lectus, St.','Madison','WI','7288');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rylee Weeks','P.O. Box 994, 7699 Non, Street','Owen Sound','Ontario','866472');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Chaney Reynolds','Ap #441-9680 Duis Road','Feira de Santana','BA','31837');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Magee Foster','5333 Enim, Road','Manavgat','Antalya','707231');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Oren Sellers','Ap #274-7029 Eget Av.','Petrópolis','Rio de Janeiro','97342');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Gannon Christian','Ap #791-280 Turpis Road','Cessnock','NSW','837340');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Valentine Langley','Ap #954-3989 Arcu. St.','Lithgow','New South Wales','X2G 3K7');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Elliott Acevedo','8621 Dignissim Avenue','Yahyalı','Kayseri','573176');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rhiannon Bowman','2717 Blandit Ave','Castelló','Comunitat Valenciana','70567');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Elliott Franks','Ap #859-3510 Maecenas Av.','Ijebu Ode','Ogun','56423');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Camden Lewis','Ap #429-7519 Luctus St.','Chambord','QC','1407');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rama Huff','P.O. Box 705, 866 Sapien. Avenue','Castelluccio Valmaggiore','Puglia','746625');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Latifah Patton','663 Fringilla Road','Jonesboro','Arkansas','71665');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Dustin Case','Ap #932-3896 Pede St.','Mata de Plátano','San José','739329');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Rylee Hatfield','P.O. Box 683, 443 Risus. Ave','Södertälje','Stockholms län','119866');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Maisie Whitfield','P.O. Box 184, 9959 Sagittis. Street','Butte','Montana','H4S 7A6');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Sebastian Burke','1034 Eu, Ave','Broken Hill','NSW','1686');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Tate Weiss','Ap #114-2140 A, Rd.','Rotterdam','Z.','48116');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('James Beck','242-7486 Sodales St.','Maranguape','Ceará','586413');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Odette Livingston','756-7228 Suspendisse Road','Okigwe','IM','9599');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kendall Donovan','Ap #666-3449 Id Rd.','Redcliffe','QLD','63223');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Jessica Mcconnell','1888 Urna. St.','Oxford','Oxfordshire','364515');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Mona Mckee','Ap #935-5833 Eu St.','Sambhal','Uttar Pradesh','2422');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Maisie Atkinson','887-9781 Massa. Street','Cambiago','Lombardia','C7X 7T7');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Miranda Cline','8953 Suspendisse Street','Sosnowiec','Sląskie','874096');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Michael Wilkins','1947 Eget St.','Sandy','UT','44457');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kadeem Reid','2629 In Rd.','Kearney','Nebraska','1406');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Colleen Mullen','317-6074 Ultricies St.','Galway','C','18211');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Virginia Baldwin','P.O. Box 490, 1516 Pellentesque Av.','Gibbons','Alberta','70390');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Pandora Kim','Ap #579-5682 Tellus. Avenue','Glendale','AZ','84-266');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Clinton Garrett','P.O. Box 412, 6137 Felis St.','Kalisz','Wielkopolskie','D2R 0KX');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Raymond Richardson','259 Nullam Rd.','Alert Bay','British Columbia','80593');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Chaim Fisher','P.O. Box 590, 1396 Quisque Street','Hamburg','Hamburg','70-821');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Callum Bond','450-2872 Nulla St.','Dubbo','NSW','899221');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Brenda Cabrera','P.O. Box 231, 7568 Ad Avenue','Mjölby','Östergötlands län','170206');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Maisie Hunter','P.O. Box 645, 4282 Non St.','Vienna','Wie','0298QS');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Noelle Schmidt','625-2027 Lectus Avenue','Minervino di Lecce','Puglia','C46 8KI');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Leigh Rutledge','4586 Aliquam Ave','Vienna','Vienna','15475');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kevin Mendez','Ap #726-7047 Vel Rd.','Buccheri','SIC','81410');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Taylor Howard','Ap #173-5275 Aliquet Ave','Anamur','Mersin','7659');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Tyrone Riley','9610 Mi Rd.','Redcliffe','QLD','1926');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Colt Vinson','Ap #940-367 Dolor St.','Cessnock','New South Wales','21930');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Caldwell Andrews','Ap #250-8187 Fusce Ave','Wiener Neustadt','Lower Austria','93321');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Nita Moses','8712 Mattis. Rd.','Cork','Munster','9267');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kareem Watkins','P.O. Box 931, 5842 Semper Ave','Berlin','BE','36403');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kyra Rowland','535-2833 Enim, Rd.','Vienna','Wie','206166');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Brock Weeks','P.O. Box 865, 330 Curabitur Rd.','Dublin','L','82915');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Shelley Walters','8811 Integer Rd.','Middelburg','Zl','842266');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kareem Garrett','P.O. Box 342, 2270 Magnis Road','Eindhoven','N.','07-300');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Kato Middleton','P.O. Box 818, 4680 Auctor St.','Liberia','Guanacaste','12094');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Caesar Carr','P.O. Box 851, 865 Mauris Street','Stalowa Wola','PK','55-016');
INSERT INTO DaltonCustomers (NAME,ADDRESS,CITY,STATE,ZIP) VALUES ('Armand Giles','P.O. Box 442, 8324 Commodo Street','Kungälv','O','1497');

INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,2114471255077256,1,'11-Aug-1989');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,8183375137547653,2,'03-Nov-1993');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (14,1478371529115570,1,'29-Jan-1995');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (16,5969259010420906,1,'16-Sep-1988');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,5955280558102661,1,'30-Mar-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,8230498073001703,1,'25-Jan-2001');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,2074093752437167,2,'04-Oct-2010');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (2,9424878524409401,1,'03-Nov-1989');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,1142115663323137,1,'28-Sep-2001');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,4918205609752072,1,'27-Oct-2013');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (6,3404722909132639,1,'15-May-2006');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (12,1118664799465073,2,'24-Sep-1992');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,1291748049358526,2,'31-Mar-2016');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,3176354000137912,2,'23-Mar-2000');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,1416535149845812,2,'12-Aug-1997');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,5032440688874987,2,'04-Mar-2008');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,5485022916562028,1,'06-Feb-1995');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,2057865013678868,1,'07-Mar-1998');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,4307277674476306,1,'11-Apr-1994');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,7613919435275926,1,'20-Jun-2012');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (9,2648132290277216,1,'16-Jan-2002');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (16,5429284920295080,1,'22-Aug-1998');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,9671134828693338,2,'04-Oct-2013');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (14,4935556567377514,1,'27-Jul-1988');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (13,4558046799567011,2,'11-Feb-2002');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (13,6449289897249805,1,'08-Dec-2012');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,6095543383724160,2,'13-May-1993');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,9757704916927551,1,'12-Apr-2002');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,8487794030871657,2,'09-Jul-2002');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,6181075593663587,1,'28-Aug-2009');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (13,4588873941037390,2,'09-Jul-1989');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,3723759150339497,2,'04-Jul-1996');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (19,9621326414247355,1,'18-Jul-1998');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (18,3619193418158425,1,'22-Nov-1999');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,4960149005055428,2,'20-Sep-2011');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,5757826380431653,1,'02-Mar-2007');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (18,9125696482757728,1,'11-Feb-1992');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,9327789909309812,1,'25-Nov-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,3355151510073079,2,'12-Jul-2007');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,1895600242747200,1,'20-Dec-1990');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (13,7452849600878027,2,'24-Nov-2015');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (18,6024393505520291,1,'09-Dec-2003');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,6017628610134125,1,'20-May-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,4034864732788669,2,'10-Aug-2000');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,3265616426037417,1,'18-Jan-1995');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,4598900965518422,1,'26-May-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,1142926377554734,2,'29-May-2011');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,7182238147490555,2,'02-Aug-2013');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (7,3518651036752595,2,'26-Jan-2000');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,9589431745310625,1,'30-Jun-2009');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (11,8748881609903442,1,'13-Sep-1999');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,5655005942616198,1,'14-Sep-2014');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,8255910049710010,2,'09-Oct-2011');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,9011074184543558,2,'30-Sep-2007');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (9,1790288115541140,1,'30-Apr-1989');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (6,4102453150682979,1,'10-May-1989');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,7104208999209934,1,'18-Feb-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,9260484803881911,1,'17-Jun-1996');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,6168406361507045,1,'04-Oct-1991');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,1574921053316858,2,'24-Jan-2010');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (14,3084024261269304,2,'15-Jan-1998');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (16,3347630931271447,1,'09-Jun-2009');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,9778843116429118,2,'07-Feb-2006');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (11,1946560045083363,2,'20-Jul-2005');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,6698485886057219,2,'23-Oct-1988');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,6818327158689500,2,'05-Sep-2012');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (9,7345695756375790,2,'09-Dec-1990');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (7,7922410058478515,1,'04-Dec-2014');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (10,4160431317157216,1,'05-Sep-2001');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,6616728752851487,2,'21-Apr-2013');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (2,3780821292764611,1,'29-Jan-1988');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,7083104815748003,1,'31-Dec-1990');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (7,4526067955626382,2,'05-Nov-2000');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,4378610303004583,2,'16-Sep-2011');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (3,1993979836503664,2,'26-Aug-2014');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,7444541085925368,1,'08-Aug-2007');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,6041028557552232,2,'21-Nov-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,5143455883695020,1,'30-Sep-2001');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (13,7637438041468462,1,'09-Oct-2010');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,2161018707686000,1,'04-Jul-2008');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (9,3269018410808510,2,'11-Mar-2015');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (19,5532068949606684,1,'03-Mar-2010');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,7910691276192666,1,'04-Oct-2002');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (17,1916582936214076,2,'14-Jun-2016');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,7602908098035389,1,'22-Feb-2008');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (20,1638975996110174,2,'13-Apr-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (4,1573806843823856,2,'01-May-2015');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,5461579706105921,2,'04-Sep-1994');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (7,1150369437204466,2,'21-Oct-2003');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (18,4169914639658398,1,'12-Mar-1994');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,2279952011174625,2,'03-May-1996');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (19,8962255948119694,1,'17-Sep-1988');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (11,9468837380409242,1,'22-Dec-1999');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,3805258054700163,2,'30-Jun-2004');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,5496489645706283,1,'20-Jan-2015');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (15,5314008833633529,1,'21-Dec-1995');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (5,2043782998290326,2,'19-Jul-1996');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (1,1863910204006565,1,'21-Jan-2013');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (8,6555595439341334,1,'22-Mar-2010');
INSERT INTO DaltonAccounts (CustomerId,AccountNumber,AccountType,DateOpened) VALUES (16,1185951539211802,2,'02-Aug-2014');

INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (8,4501997,1,'01-Nov-1988');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (19,5304888,2,'15-May-2012');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (42,5145133,2,'02-Nov-1990');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (15,6445380,4,'28-Aug-2013');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (45,579191,1,'22-Aug-1989');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (45,219386,3,'08-Mar-2017');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (35,2272228,2,'24-Jun-2008');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (25,7517171,3,'08-Dec-2014');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (8,9952836,2,'23-Oct-2003');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (23,291581,1,'28-Jun-2004');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (14,7030560,3,'13-Feb-1989');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (43,3346282,4,'25-Apr-2007');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (36,8891639,4,'12-Oct-1996');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (47,4468632,2,'02-Sep-2004');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (22,9734280,4,'04-Apr-1992');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (28,9171793,2,'05-Jan-1998');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (18,8067039,4,'10-May-1995');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (19,2385836,1,'31-Mar-2011');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (5,7673745,4,'01-Feb-1998');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (14,5570010,1,'29-May-2007');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (27,5246448,2,'06-Jun-2006');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (42,2028643,4,'13-Dec-1988');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (41,7847787,1,'19-Jun-2005');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (21,1349243,1,'21-Oct-1990');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (9,4734843,3,'19-Nov-2001');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (9,645787,2,'04-Jun-2016');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (15,8620377,2,'21-Nov-1990');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (34,5734028,3,'23-Jun-1991');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (43,3743785,3,'12-Oct-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (27,4269759,2,'20-Oct-2006');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (39,4149567,2,'05-Mar-2006');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (49,229995,4,'20-Jan-1991');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (27,1741293,2,'12-Oct-1995');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (10,5288252,3,'10-Feb-2002');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (32,6697798,2,'12-Jan-2006');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (6,6640447,2,'07-Feb-1991');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (3,3922322,4,'12-Jun-2016');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (14,7105839,2,'01-Jun-2012');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (44,459907,2,'31-May-1989');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (10,5606621,3,'09-Oct-2004');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (47,4180237,3,'27-Apr-2006');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (9,742018,4,'14-Sep-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (24,7601366,1,'26-May-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (26,3648298,2,'21-Jun-2009');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (46,5030624,3,'01-Jan-2002');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (36,183663,3,'14-Feb-1998');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (8,9906725,1,'01-Jan-2016');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (34,76684,1,'31-Jul-2009');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (40,1653763,2,'07-Sep-2002');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (41,105532,1,'04-May-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (45,3284053,2,'25-Jul-2013');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (1,2216891,3,'13-Jul-2009');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (15,2385257,2,'24-Jun-1997');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (48,9742284,1,'16-Jun-1988');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (20,2083368,3,'15-Nov-1994');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (32,3181068,2,'02-Sep-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (12,3810518,1,'24-Feb-2012');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (7,170316,1,'14-May-2011');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (1,2021826,3,'14-Dec-2002');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (48,693564,4,'19-Nov-2004');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (42,2727414,1,'07-May-1990');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (21,9172750,4,'24-Dec-1996');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (26,1093630,1,'05-Mar-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (49,3720853,2,'06-May-2015');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (23,1429850,3,'24-May-2007');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (17,7717741,3,'22-May-1988');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (48,4984889,2,'19-May-1998');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (12,5527870,3,'28-Oct-1998');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (40,5716443,2,'14-Oct-2001');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (6,2717715,3,'10-Aug-1995');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (26,2993794,4,'15-Mar-1997');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (37,2315878,3,'12-Mar-1996');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (11,6887018,1,'23-Aug-2012');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (35,1646844,2,'06-May-2015');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (38,4343811,3,'13-Jul-1996');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (2,2339544,1,'25-Oct-2002');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (1,6369807,4,'29-May-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (41,1694786,4,'01-Jan-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (39,1501012,1,'16-Nov-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (22,8664293,4,'04-Jun-2008');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (33,8458052,2,'12-Oct-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (19,1650244,1,'22-Jun-1992');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (3,5503175,2,'03-Oct-2004');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (5,7388334,2,'12-Jan-2003');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (44,4837427,2,'17-Jan-1997');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (41,8983766,4,'29-Dec-2016');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (5,253888,4,'22-Jun-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (25,4717212,3,'02-Sep-2011');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (44,3875732,4,'13-Sep-2015');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (1,1844745,3,'13-Jul-2017');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (24,5540849,3,'26-Dec-2007');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (22,6822742,1,'11-Nov-2005');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (5,1727816,4,'10-Aug-2009');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (45,5386284,4,'20-Feb-1995');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (28,7668024,2,'15-Aug-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (35,4607747,4,'27-Dec-2000');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (46,524269,4,'13-Jan-1988');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (16,2548322,3,'18-Jan-2010');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (6,5979698,1,'20-Jan-1989');
INSERT INTO DaltonTransactions (AccountId,Amount,TransactType,TransactionDate) VALUES (45,9901085,3,'20-Sep-2013');
